# Generated by Django 4.2.3 on 2023-08-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travelapp', '0002_delete_ourteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='ourteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200)),
                ('images', models.ImageField(upload_to='images')),
                ('descr', models.TextField()),
            ],
        ),
    ]
